- name: Connect to AWS VPN
  hosts: all
  tasks:
    - name: install epel
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: latest
    - name: update dnf packages
      dnf:
        update_cache: true
        update_only: true
        state: latest
    - name: install wireguard
      dnf:
        name: wireguard-tools
        state: latest